// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType_Bath;
//
//    var Bathitem = Bathitem.FromJson(jsonString);

namespace QuickType_Bath
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Bathitem
    {
        [JsonProperty("bathroom_id")]
        public int bath_id { get; set; }

        [JsonProperty("building_id")]
        public int build_id { get; set; }

        [JsonProperty("bathroom_name")]
        public string bathroom_name { get; set; }
    }

    public partial class Bathitem
    {
        public static Bathitem[] FromJson(string json) => JsonConvert.DeserializeObject<Bathitem[]>(json, QuickType_Bath.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Bathitem[] self) => JsonConvert.SerializeObject(self, QuickType_Bath.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}