// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType_Build;
//
//    var Builditem = Builditem.FromJson(jsonString);

namespace QuickType_Build
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Builditem
    {
        [JsonProperty("building_id")]
        public int build_id { get; set; }

        [JsonProperty("name")]
        public string build_name { get; set; }
    }

    public partial class Builditem
    {
        public static Builditem[] FromJson(string json) => JsonConvert.DeserializeObject<Builditem[]>(json, QuickType_Build.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Builditem[] self) => JsonConvert.SerializeObject(self, QuickType_Build.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}