// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var Item = Item.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Item
    {
        [JsonProperty("dispenser_id")]
        public int Disid { get; set; }

        [JsonProperty("level")]
        public int Level { get; set; }

        [JsonProperty("battery_level")]
        public int Battery { get; set; }

        [JsonProperty("bathroom_id")]
        public int Bathid { get; set; }

        [JsonProperty("dispenser_type")]
        public string Distype { get; set; }

        [JsonProperty("last_updated")]
        public string Update { get; set; }

        [JsonProperty("mac_address")]
        public string Addr { get; set; }
    }

    public partial class Item
    {
        public static Item[] FromJson(string json) => JsonConvert.DeserializeObject<Item[]>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Item[] self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}